language: ruby
rvm:
  - 2.4.9
  - 2.6.5
  - 2.7.0

branches:
  only:
    - master
    - develop

addons:
  postgresql: "9.4"

env:
  - REDMINE_VER=3.4-stable
  - REDMINE_VER=4.0-stable

install: "echo skip bundle install"

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
services:
  - redis-server

script:
  - export TESTSPACE=`pwd`/testspace
  - export NAME_OF_PLUGIN=redmine_bots
  - export PATH_TO_PLUGIN=`pwd`
  - export PATH_TO_REDMINE=$TESTSPACE/redmine
  - mkdir $TESTSPACE
  - cp test/support/* $TESTSPACE/
  - bash -x ./travis.sh
